//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Program_Menber
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class memberorder
    {
        [DisplayName("序號")]
        
        public int oid { get; set; }
        [DisplayName("日期")]
        [Required]
        public string odate { get; set; }
        [DisplayName("會員編號")]
        [Required]
        public Nullable<int> omid { get; set; }
        [DisplayName("會員姓名")]
        [Required]
        public string oname { get; set; }
        [DisplayName("產品")]
        [Required]
        public string oproduct { get; set; }
        [DisplayName("廟宇")]
        [Required]
        public string otem { get; set; }
        [DisplayName("數量")]
        [Required]
        public Nullable<int> ounit { get; set; }
        [DisplayName("金額")]
        [Required]
        public Nullable<int> opayment { get; set; }
        [DisplayName("平台是否收到郵件")]
        [Required]
        public string ofin { get; set; }
        [DisplayName("完成照片")]
        [Required]
        public string opic { get; set; }
        [DisplayName("備註")]
        [Required]
        public string odetail { get; set; }
        [DisplayName("會員信箱")]
        [EmailAddress]
        [Required]
        public string omemail { get; set; }
    }
}
