//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Program_Menber
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class member
    {
        [DisplayName("序號")]
        [Required]
        public int mid { get; set; }
        [DisplayName("註冊姓名")]
        [Required(ErrorMessage = "輸入正確姓名")]
        public string mname { get; set; }
        [DisplayName("註冊會員生日")]
        [Required(ErrorMessage = "輸入正確生日")]
        public string mbirth { get; set; }
        [DisplayName("註冊會員性別")]
        [Required(ErrorMessage = "輸入正確會員性別")]
        public string mgender { get; set; }
        [DisplayName("註冊會員信箱")]
        [EmailAddress]
        [Required(ErrorMessage = "輸入正確會員信箱")]
        public string memail { get; set; }
        [DisplayName("註冊會員手機")]
        [Phone]
        [Required(ErrorMessage = "輸入正確會員手機")]
        public string mphone { get; set; }
        [DisplayName("註冊會員密碼")]
        [Required(ErrorMessage = "輸入正確會員密碼")]
        public string mpw { get; set; }
        [DisplayName("註冊會員城市")]
        [Required(ErrorMessage = "輸入正確會員城市")]
        public string mcity { get; set; }
        [DisplayName("註冊會員圖片")]
        [Required(ErrorMessage = "輸入正確會員圖片")]
        public string mpic { get; set; }
    }
}
