//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Program_Menber
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int pid { get; set; }
        public string parea { get; set; }
        public string pcity { get; set; }
        public string pcate { get; set; }
        public string ptemp { get; set; }
        public string pname { get; set; }
        public int pprice { get; set; }
        public string ppic { get; set; }
        public string pintroduce { get; set; }
        public string pwebsite { get; set; }
        public string pdetail { get; set; }
    }
}
