//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Program_Menber
{
    using System;
    using System.Collections.Generic;
    
    public partial class 籤詩
    {
        public int sid { get; set; }
        public string s籤號 { get; set; }
        public string s籤等 { get; set; }
        public string s內文 { get; set; }
        public string s籤解 { get; set; }
    }
}
